export class FacultyProfile {
  public select: boolean | undefined;
  public id: number | undefined;
  public photo: string | undefined;
  // public idNo: number| undefined;
  public krNo: number | undefined;
  public rfNo: string | undefined;
  public moze: string | undefined;
  public itsId: number | undefined;
  public fullName: string | undefined;
  public fullNameArabic: string | undefined;
  // public mobile1: string| undefined;
  public mobileNo: string | undefined;
  // public mobile2: string| undefined;
  public whatsappNo: string | undefined;
  // public email: string| undefined;
  public emailAddress: string | undefined;
  public watan: string | undefined;
  public watanArabic: string | undefined;
  public muqaam: string | undefined;
  public muqaamArabic: string | undefined;
  //public jm_Ns_Id: number| undefined;
  public trNo: number | undefined;
  // public daras_darajah: string| undefined;
  public farigDarajah: string | undefined;
  public mz_idara_color: string | undefined;
  public currentDarajah: string | undefined;
  public fariqYear: number | undefined;
  // public sanadJamea: string| undefined;
  public alJameaDegree: string | undefined;
  public khidmatMonth: string | undefined;
  public khidmatYear: number | undefined;
  public totalTayeenYear: number | undefined;
  public educationalQualification: string | undefined;
  public dob: string | undefined;
  public dobArabic: string | undefined;
  public age: number | undefined;
  public bloodGroup: string | undefined;
  //public address: string| undefined;
  public khidmatMauzeAddress: string | undefined;
  public hifzSanadYear: number | undefined;
  //public flatNo: string| undefined;
  public khidmatMauzeHouseStatus: string | undefined;
  public accomodation: string | undefined;
  public jaman: string | undefined;
  public maritalStatus: string | undefined;
  public mafsuhiyatYear: number | undefined;
  public fatherItsId: number | undefined;
  public motherItsId: number | undefined;
  public wifeItsId: number | undefined;
  public wifeName: string | undefined;
  public wazifa: number | undefined;
  public bankAccountNumber: string | undefined;
  public bankAccountName: string | undefined;
  public elq: string | undefined;
  public tahfeezJamea_Nisaab_Camp: string | undefined;
  public atfaal: string | undefined;
  public talimAlQuran: string | undefined;
  public officeWork: string | undefined;
  public activeStatus: boolean | undefined;
  public passportName: string | undefined;
  public passportNumber: string | undefined;
  public dateOfIssue: string | undefined;
  public dateOfExpiry: string | undefined;
  public placeOfIssue: string | undefined;
  public dobPassport: string | undefined;
  public nationality: string | undefined;
  public department: string | undefined;
  //public itsIdara: string| undefined;
  public its_preferredIdara: string | undefined;

  public shortSanad: string | undefined;
  public title: string | undefined;
  public tayeenMonth: string | undefined;
  public tayeenYear: number | undefined;
  public lightServiceNo: string | undefined;
  public haj_ul_nafs: string | undefined;
  public haj_ul_badal: string | undefined;
  public totalHaj: string | undefined;
  public dept1: string | undefined;
  public dept2: string | undefined;
  public dept3: string | undefined;
  public jamaat: string | undefined;
  public jamiat: string | undefined;
  public ho: string | undefined;
  public past_Moze_1: string | undefined;
  public past_Moze_2: string | undefined;
  public past_Moze_3: string | undefined;
  public past_Moze_4: string | undefined;
  public currentMoze: string | undefined;
  public previousMawaze: string | undefined;
  public category: string | undefined;
  public ifsc: string | undefined;
  public bankName: string | undefined;
  public panCard: string | undefined;
  //public venueId: string| undefined;
  //public venueId_1: number| undefined;
  public venueId: number | undefined;
  public grossSalary: number | undefined;
  public rentAllowance: number | undefined;
  public marriageAllowance: number | undefined;
  public mumbaiAllowance: number | undefined;
  public professionTax: number | undefined;
  public tds: number | undefined;
  public qardanHasanah: number | undefined;
  public marafiqKhairiyah: number | undefined;
  public sabeel: number | undefined;
  public bqhs: number | undefined;
  public deptVenueId: number | undefined;
  public deptVenueName: string | undefined;
  //public itsIdara_1: string| undefined;

  public mz_idara: string | undefined;

  public currency: string | undefined;
  public isMahadWazifa: boolean | undefined;
  public salaryTag: number | undefined;
  public salaryTagName: string | undefined;
  // public email_2: string| undefined;
  public officialEmailAddress: string | undefined;
  public haddiyatYear: number | undefined;
  public wafd_TrainingMasool: number | undefined;
  public maqaam: string | undefined;
  public domacileParents: string | undefined;
  public domacileParentsAddress: string | undefined;
  public watanAddress: string | undefined;
  public bankBranch: string | undefined;
  public accountType: string | undefined;
  public totalKhidmatYear: number | undefined;

  public personalHouseAddress: string | undefined;
  public personalHouseArea: string | undefined;
  public personalHouseType: string | undefined;
  public personalHouseStatus: string | undefined;
  public venueProgram: string | undefined;
  public its_idaras: string | undefined;
  public batchId: string | undefined;
  public khdimatMauzeHouseType: string | undefined;
  public dojGregorian: Date | undefined;
  public c_codeWhatsapp: string | undefined;
  public aboutYourSelf: string | undefined;
  public qismTahfeez: string | undefined;
  public mahad_khidmatYear: string | undefined;
  public chequeAttachment: string | undefined;
  public passportcopy: string | undefined;
  public personalityReport: string | undefined;
  public personalityType: string | undefined;
  public activeStatusString: string | undefined;
  public workTypeId: number| undefined;
  public programList: Array<string> | undefined;
  public programs: string| undefined;
  public mainProgram: string| undefined;


  public search_mahadkg: boolean | undefined;
  public search_mahadwafd: boolean | undefined;
  public search_mahadother: boolean | undefined;
  public search_mahadrecruited: boolean | undefined;
  public search_mahadrecruitedteacher: boolean | undefined;
  public search_moze: Array<string> | undefined;
  public search_farigDarajah: Array<string> | undefined;
  public search_Active: boolean | undefined;
  public search_Inactive: boolean | undefined;

  public search_tayeeninmahadDD: Array<string> | undefined;
  public search_khidmatinmahadDD: Array<string> | undefined;
  public search_khidmatYearDD: Array<string> | undefined;
  public search_hifzSanadYearDD: Array<string> | undefined;
  public search_dawattileDD: Array<string> | undefined;
  public search_ageDD: Array<string> | undefined;
  public search_nationalityDD: Array<string> | undefined;
  public search_qismTahfeezDD: Array<string> | undefined;
  public search_categoryDD: Array<string> | undefined;
  public search_aljameaDegreeDD: Array<string> | undefined;
  public search_trainingDarajaDD: Array<string> | undefined;
  public search_dawatTitleDD: Array<string> | undefined;
  public search_houseStatusDD: Array<string> | undefined;
  public search_houseTypeDD: Array<string> | undefined;
  public search_housestatusPersonalDD: Array<string> | undefined;
  public search_houseTypePersonalDD: Array<string> | undefined;
  public search_itsIdDD: Array<string> | undefined;
  public search_batchIdDD: Array<string> | undefined;
  public search_nameDD: Array<string> | undefined;




  constructor() {}
}
